spring:
  application:
    name: ReciGuard
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://reciguard-db.czouas0eqnqo.ap-northeast-2.rds.amazonaws.com:3306/reciguard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: reciguard
    password: tavereciguard
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.springframework: DEBUG

  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: never
      platform: sql
