spring:
  application:
    name: ReciGuard
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  datasource:
    url: jdbc:mysql://localhost:3306/RECIGUARD?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: danchoo12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.springframework: DEBUG

  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: always
      platform: sql

